application: roadshow-demo
version: 03-endpoints
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1s"

libraries:
  - name: webapp2
    version: latest
  - name: pycrypto
    version: latest
  - name: endpoints
    version: latest


skip_files:
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*\.sw[op]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^app/bower_components/.*
  - ^node_modules/.*


handlers:
  # Endpoints API path
  - url: /_ah/spi/.*
    script: main.endpoints_launcher

  - url: /.*
    script: main.app
    secure: always
    # necessary, otherwise, even if logged in,
    # users.get_current_user() responds None
    login: required